def xor_string(s, key_str):
    key_bytes = key_str.encode('ascii')
    key_len = len(key_bytes)
    
    result = ""
    
    # Encrypt the string content
    for i, char in enumerate(s):
        # XOR the character's ASCII value with the repeating key
        key_byte = key_bytes[i % key_len]
        encrypted_char = ord(char) ^ key_byte
        result += f"0x{encrypted_char:02x}, "
    
    # Encrypt the null-terminator (0x00)
    # 0 ^ key[last_char_index % key_len]
    key_byte = key_bytes[len(s) % key_len]
    encrypted_null = 0 ^ key_byte
    result += f"0x{encrypted_null:02x}"
    
    return f"{{ {result} }};"

KEY_STRING = "bananenbrot"
PW = "cysLFHNW25!123"
PROMPT = "Please enter the password to access the secure system: "
GRANT = "Access Granted. Welcome to the secure area."
DENY = "Access Denied. Incorrect password."
SECRET = "The nuclear launch codes are: Hamburger Banana"

print(f"// --- Generated by encrypt_strings.py ---")
print(f"// --- Key: \"{KEY_STRING}\" ---")
print(f"char enc_pw[] = {xor_string(PW, KEY_STRING)}")
print(f"char enc_prompt[] = {xor_string(PROMPT, KEY_STRING)}")
print(f"char enc_grant[] = {xor_string(GRANT, KEY_STRING)}")
print(f"char enc_deny[] = {xor_string(DENY, KEY_STRING)}")
print(f"char enc_secret[] = {xor_string(SECRET, KEY_STRING)}")

